# Generated by Django 2.2.10 on 2024-05-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0002_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200, verbose_name='密码'),
        ),
    ]
