# Generated by Django 2.2.10 on 2024-06-01 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookList', '0002_bookbasic_click_count'),
        ('UserInfo', '0003_auto_20240530_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='性别')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='点击时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookList.BookBasic', verbose_name='书籍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserInfo.User', verbose_name='用户')),
            ],
        ),
    ]
