# Generated by Django 2.2.10 on 2024-06-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0004_userbookclick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookclick',
            name='gender',
        ),
    ]
