# Generated by Django 2.2.10 on 2024-04-16 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('author', models.CharField(max_length=200, verbose_name='作者')),
                ('type', models.CharField(choices=[('Xuanhuan', '玄幻'), ('Qihuan', '奇幻'), ('Wuxia', '武侠'), ('Xianxia', '仙侠'), ('Dushi', '都市'), ('Xianshi', '现实'), ('Junshi', '军事'), ('Lishi', '历史'), ('Youxi', '游戏'), ('Tiyu', '体育'), ('Kehuan', '科幻'), ('Wuxian', '诸天无限'), ('Xuanyi', '悬疑灵异'), ('Qing', '轻小说')], max_length=20, verbose_name='类型')),
                ('description', models.TextField(verbose_name='简介')),
                ('cover_image_url', models.CharField(max_length=500, verbose_name='封面路径')),
                ('content_url', models.CharField(max_length=500, verbose_name='内容路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content', models.TextField(verbose_name='章节内容')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookList.BookBasic', verbose_name='书籍')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
