# Generated by Django 2.2.10 on 2024-06-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookbasic',
            name='click_count',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
    ]
